return {
  {
    -- 'folke/noice.nvim',
    -- event = 'VeryLazy',
    -- -- config = function()
    -- --   require 'custom.configs.noice'
    -- -- end,
    -- opts = {
    --   -- stylua: ignore
    --   keys = {
    --     { "<S-Enter>",   function() require("noice").redirect(vim.fn.getcmdline()) end,                 mode = "c",                 desc = "Redirect Cmdline" },
    --     { "<leader>snl", function() require("noice").cmd("last") end,                                   desc = "Noice Last Message" },
    --     { "<leader>snh", function() require("noice").cmd("history") end,                                desc = "Noice History" },
    --     { "<leader>sna", function() require("noice").cmd("all") end,                                    desc = "Noice All" },
    --     { "<leader>snd", function() require("noice").cmd("dismiss") end,                                desc = "Dismiss All" },
    --     { "<c-f>",       function() if not require("noice.lsp").scroll(4) then return "<c-f>" end end,  silent = true,              expr = true,              desc = "Scroll forward",  mode = { "i", "n", "s" } },
    --     { "<c-b>",       function() if not require("noice.lsp").scroll(-4) then return "<c-b>" end end, silent = true,              expr = true,              desc = "Scroll backward", mode = { "i", "n", "s" } },
    --   },
    -- },
    -- dependencies = {
    --   {
    --     'MunifTanjim/nui.nvim',
    --     lazy = true,
    --   },
    --   {
    --     'rcarriga/nvim-notify',
    --     config = function()
    --       require('notify').setup {
    --         background_colour = '#000000',
    --       }
    --     end,
    --     keys = {
    --       {
    --         '<leader>un',
    --         function()
    --           require('notify').dismiss { silent = true, pending = true }
    --         end,
    --         desc = 'Dismiss all Notifications',
    --       },
    --     },
    --     opts = {
    --       timeout = 3000,
    --       max_height = function()
    --         return math.floor(vim.o.lines * 0.75)
    --       end,
    --       max_width = function()
    --         return math.floor(vim.o.columns * 0.75)
    --       end,
    --       on_open = function(win)
    --         vim.api.nvim_win_set_config(win, { zindex = 100 })
    --       end,
    --     },
    --     lazy = true,
    --   },
    -- },
  },
}
-- vim: ts=2 sts=2 sw=2 et
