return {}
-- return {
--   {
--     'folke/noice.nvim',
--     event = 'VeryLazy',
--     dependencies = {
--       'MunifTanjim/nui.nvim',
--       'rcarriga/nvim-notify',
--     },
--     opts = {
--       lsp = {
--         -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
--         override = {
--           ['vim.lsp.util.convert_input_to_markdown_lines'] = true,
--           ['vim.lsp.util.stylize_markdown'] = true,
--           ['cmp.entry.get_documentation'] = true, -- requires hrsh7th/nvim-cmp
--         },
--       },
--       -- you can enable a preset for easier configuration
--       presets = {
--         bottom_search = true, -- use a classic bottom cmdline for search
--         command_palette = true, -- position the cmdline and popupmenu together
--         long_message_to_split = true, -- long messages will be sent to a split
--         inc_rename = false, -- enables an input dialog for inc-rename.nvim
--         lsp_doc_border = false, -- add a border to hover docs and signature help
--       },
--     },
--     -- stylua: ignore
--     keys = {
--       { "<S-Enter>",  function() require("noice").redirect(vim.fn.getcmdline()) end,                mode = "c",                 desc = "Redirect Cmdline" },
--       { "<leader>ul", function() require("noice").cmd("last") end,                                  desc = "[U]I [L]ast Message" },
--       { "<leader>uh", function() require("noice").cmd("history") end,                               desc = "[U]I [H]istory" },
--       { "<leader>ua", function() require("noice").cmd("all") end,                                   desc = "[U]I [A]ll" },
--       -- { "<leader>ud", function() require("noice").cmd("dismiss") end,                                desc = "[U]I [D]ismiss All" },
--       -- { "<c-f>",       function() if not require("noice.lsp").scroll(4) then return "<c-f>" end end,  silent = true,              expr = true,              desc = "Scroll forward",  mode = { "i", "n", "s" } },
--       -- { "<c-b>",       function() if not require("noice.lsp").scroll(-4) then return "<c-b>" end end, silent = true,              expr = true,              desc = "Scroll backward", mode = { "i", "n", "s" } },
--     },
--   },
-- }
-- vim: ts=2 sts=2 sw=2 et
