<?php
/*
 * This document has been generated with
 * https://mlocati.github.io/php-cs-fixer-configurator/#version:3.48.0|configurator
 * you can change this configuration by importing this file.
 */
$config = new PhpCsFixer\Config();

return $config
	->setIndent("\t")
	->setRules([
		'align_multiline_comment'                       => true,
		'array_indentation'                             => true,
		'array_syntax'                                  => ['syntax' => 'short'],
		'backtick_to_shell_exec'                        => true,
		'binary_operator_spaces'                        => ['default' => 'align_single_space_minimal'],
		'blank_line_after_namespace'                    => true,
		'blank_line_after_opening_tag'                  => true,
		'blank_line_before_statement'                   => ['statements' => ['break', 'continue', 'declare', 'return', 'try', 'if', 'foreach', 'for']],
		'braces'                                        => ['allow_single_line_closure' => true, 'position_after_anonymous_constructs' => 'next', 'position_after_control_structures' => 'next', 'position_after_functions_and_oop_constructs' => 'next'],
		'cast_spaces'                                   => true,
		'class_definition'                              => true,
		'clean_namespace'                               => true,
		'compact_nullable_typehint'                     => true,
		'concat_space'                                  => ['spacing' => 'one'],
		'constant_case'                                 => true,
		'echo_tag_syntax'                               => true,
		'elseif'                                        => true,
		'encoding'                                      => true,
		'explicit_string_variable'                      => true,
		'full_opening_tag'                              => true,
		'function_declaration'                          => true,
		'heredoc_to_nowdoc'                             => true,
		'indentation_type'                              => true,
		'line_ending'                                   => true,
		'linebreak_after_opening_tag'                   => true,
		'lowercase_cast'                                => true,
		'lowercase_keywords'                            => true,
		'lowercase_static_reference'                    => true,
		'magic_constant_casing'                         => true,
		'magic_method_casing'                           => true,
		'method_argument_space'                         => true,
		'method_chaining_indentation'                   => true,
		'multiline_comment_opening_closing'             => true,
		'multiline_whitespace_before_semicolons'        => true,
		'native_function_casing'                        => true,
		'native_function_type_declaration_casing'       => true,
		'new_with_braces'                               => true,
		'no_alias_language_construct_call'              => true,
		'no_blank_lines_after_phpdoc'                   => true,
		'no_closing_tag'                                => true,
		'no_empty_comment'                              => true,
		'no_empty_phpdoc'                               => true,
		'no_empty_statement'                            => true,
		'no_extra_blank_lines'                          => ['tokens' => ['extra']],
		'no_leading_import_slash'                       => true,
		'no_leading_namespace_whitespace'               => true,
		'no_multiline_whitespace_around_double_arrow'   => true,
		'no_singleline_whitespace_before_semicolons'    => true,
		'no_space_around_double_colon'                  => true,
		'no_spaces_after_function_name'                 => true,
		'no_spaces_around_offset'                       => true,
		'no_spaces_inside_parenthesis'                  => true,
		'no_trailing_comma_in_singleline'               => true,
		'no_trailing_whitespace'                        => true,
		'no_trailing_whitespace_in_comment'             => true,
		'no_unused_imports'                             => true,
		'no_useless_nullsafe_operator'                  => true,
		'no_whitespace_before_comma_in_array'           => true,
		'no_whitespace_in_blank_line'                   => true,
		'normalize_index_brace'                         => true,
		'object_operator_without_whitespace'            => true,
		'ordered_imports'                               => true,
		'phpdoc_align'                                  => true,
		'phpdoc_indent'                                 => true,
		'phpdoc_inline_tag_normalizer'                  => true,
		'phpdoc_order'                                  => true,
		'phpdoc_trim'                                   => true,
		'phpdoc_trim_consecutive_blank_line_separation' => true,
		'phpdoc_types'                                  => true,
		'return_type_declaration'                       => true,
		'semicolon_after_instruction'                   => true,
		'short_scalar_cast'                             => true,
		'simple_to_complex_string_variable'             => true,
		'single_blank_line_at_eof'                      => true,
		'single_blank_line_before_namespace'            => true,
		'single_class_element_per_statement'            => true,
		'single_import_per_statement'                   => true,
		'single_line_after_imports'                     => true,
		'single_quote'                                  => true,
		'single_space_after_construct'                  => true,
		'single_trait_insert_per_statement'             => true,
		'space_after_semicolon'                         => true,
		'switch_case_space'                             => true,
		'ternary_operator_spaces'                       => true,
		'trailing_comma_in_multiline'                   => true,
		'trim_array_spaces'                             => true,
		'unary_operator_spaces'                         => true,
		'visibility_required'                           => true,
		'whitespace_after_comma_in_array'               => true,
		'yoda_style'                                    => true,
	])
	->setFinder(
		PhpCsFixer\Finder::create()
			->in(__DIR__)
		// ->exclude([
		//     'folder-to-exclude',
		// ])
		// ->append([
		//     'file-to-include',
		// ])
	)
;
